### ISSUE TITLE
Why create docker volume, and nothing in volume directory? and question about migrate dst-server.

### ISSUE THREAD

**Issue by test482** [mathielo/dst-dedicated-server#21]
I am sorry for my poor English.

* **What is the host OS?** (Windows, Linux, Mac? Which version?)
OS: Ubuntu 18.04.4 LTS x86_64
Docker version: 19.03.8
docker-compose version: 1.25.4, build 8d51620a

* **Where are you running it?** (Local/own computer, VPS, AWS?)
VPS

* **logs**
[Master_server_log.txt](https://github.com/mathielo/dst-dedicated-server/files/4380671/Master_server_log.txt)
[Caves_server_log.txt](https://github.com/mathielo/dst-dedicated-server/files/4380672/Caves_server_log.txt)

I started a dst server three months ago, everything is fine.

but, today i want migrate dst-Server to my new VPS. At the beginning, i don't know how to migrate, when i run `docker volume ls`, i see two volumes listed:
![docker-volume](https://user-images.githubusercontent.com/23721835/77531767-6d0b5900-6ece-11ea-8077-72c5b0a19fe7.png)

and when i run `docker inspect dst_master` and `docker inspect dst_caves`:
![dst_master](https://user-images.githubusercontent.com/23721835/77531964-d55a3a80-6ece-11ea-844b-0c76aa8ca2c5.png)
![dst_caves](https://user-images.githubusercontent.com/23721835/77532030-08043300-6ecf-11ea-86d9-b223041be68a.png)

when i `cd` to the directory which listed on `docker inspect`: 
```
root@aliyun-beijing-ecs:/var/lib/docker/volumes/4fe500065c7034d12927b5d58667d18b1e2b48b9326ea8e155cb8f8522697d50/_data# tree .
.
└── DSTWhalesCluster

1 directory, 0 files
```
it is nothing in there, only one directory `DSTWhalesCluster`, same as other volume.

My doubt is i see below text on `docker-compose.yml`:
```
    volumes:
      - ./DSTClusterConfig:/home/dst/.klei/DoNotStarveTogether/DSTWhalesCluster
      - ./volumes/mods:/home/dst/server_dst/mods
```
it's means should only use the host directory to be `DSTClusterConfig`, right? why there have two volume created?

and i have other question, if i want move dst-Server for one VPS to other VPS, do I only need to package the entire folder `dst-dedicated-server`, and re-run it?

**Comment by mathielo** [comment]
Hey @test482 sorry for the delay. Each volume plays an important role.

`./DSTClusterConfig:/home/dst/.klei/DoNotStarveTogether/DSTWhalesCluster`:
This is where the cluster settings are stored, and they are shared by both Master and Caves shards. These files live in the project and are mounted into the shards so they can load these settings.

`./volumes/mods:/home/dst/server_dst/mods`:
You probably don't see this because you don't have any mods enabled, but if you had you'd also see that there. This volume is for mods to be reused between shards without unnecessary re-download every time you start the game.

Regarding your question about moving VPS: Moving the entire `dst-dedicated-server` folder should work. Some people had issues with that before due to system permissions, so just check file ownership and permissions after moving to make sure the correct users have the right access.

**Comment by test482** [comment]
Thanks for your reply @mathielo .

I already knew `./DSTClusterConfig` `./volumes/mods` roles played.

My doubt point is the third volume in the picture `docker volume ls`, the 3rd volume isn't on Game folder, and the 3rd is useless, nothing in it. also i cannot see any part command about the 3rd volume on docker-compose.yml.

I think the 3rd volume should not be created, am i right?

![image](https://user-images.githubusercontent.com/23721835/79253454-d3740d80-7eb5-11ea-9a9e-d7879e3e6a10.png)
