### ISSUE TITLE
"exec user process caused: exec format error" on ARM system

### ISSUE THREAD

**Issue by ThaiDat** [mathielo/dst-dedicated-server#34]
Hi. I am trying to deploy my own dedicated server. But I got the below error.

* **What is the host OS?** (Windows, Linux, Mac? Which version?)
Oracle Linux 8 (ARM)

* **Where are you running it?** (Local/own computer, VPS, AWS?)
VPS

* **Please paste the logs** [as code snippets](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) for both `Master` and `Caves` shards, found at:

```
dst_caves     | standard_init_linux.go:228: exec user process caused: exec format error
dst_master    | standard_init_linux.go:228: exec user process caused: exec format error
dst_master exited with code 1
dst_caves exited with code 1
```

**Comment by mathielo** [comment]
Hey @ThaiDat, I researched a bit and it seems the issue is that the Docker image was built _based off and for_ a different architecture. Apparently [Docker images needs to be built separately for different architectures](https://stackoverflow.com/a/52793714/2752041). As of now this project doesn't support ARM, unfortunately. I will try to look into it at some point :)

**Comment by ThaiDat** [comment]
I gave up some days ago. I have switched to another machine.

This issue is because Steam's executable files do not support ARM architecture (it is i386). I have tried to use the qemu emulator to run those Steam files inside the Dockerfile and rebuild it but still not successful. Maybe I have made some mistakes like using qemu inside the Dockerfile (maybe it should run outside the Dockerfile, maybe the Dockerfile should be built on x86 system with ARM target, etc).

Hope to see the support in the future.
