### ISSUE TITLE
Server Save Slot not working

### ISSUE THREAD

**Issue by jh-code** [mathielo/dst-dedicated-server#5]
Hi, so I edited cluster.ini to use save slot 2. I shut down the server and started it back up, and it is still using the world from slot 1. I was assuming it would generate a new world, and save the other world in slot 1, however that is not what is happening. Is there something else I need to do?

**Comment by mathielo** [comment]
Hey @jh-code, that's actually one very interesting questioning!

The `server_save_slot`  attribute is present it `cluster.ini` file because... well, honestly it's mostly because I've seen it around in other tutorials when building this project here, but never really used it. Now that you mentioned it, I ran some tests and (I might be wrong, but) it seems that this attribute isn't really taken into account by dedicated servers; I even opened a thread in Klei's forums ([check it out](https://forums.kleientertainment.com/topic/91021-dedicated-servers-server_save_slot-does-it-matter-at-all/)) to see if anyone else bumped into this before.

--- 

Now if you want your problem solved (to be able to have different worlds/save simultaneously), you could do as I've done: just clone the repo again in another directory, and config it the way you want your new server to be. Once all the dependencies are installed in your host computer (docker, git, etc) it's only a matter of tweaking the config files to your liking. 

Keep in mind that if you want to have _both_ worlds running at the same time you need to change [the network](https://github.com/mathielo/dst-dedicated-server/blob/master/docker-compose.yml#L37) and [containers' names](https://github.com/mathielo/dst-dedicated-server/blob/master/docker-compose.yml#L18) to new unique ones, otherwise Docker will complain as "You already have a `dst_master` container running"  when trying to spin up the second world. 

You'll also need another `cluster_token.txt` if running them at the same time, as each server needs their own.

Hope this helps!

**Comment by jh-code** [comment]
Ah, not sure why I didn't think of just cloning the repo again ha. Thank you!

**Comment by mathielo** [comment]
Apparently `server_save_slot` isn't really used by dedicated servers, so I removed it in #6 when making some improvements to the docs. Thanks for bringing it up - and sorry it was misleading / caused confusion.
